name: Feature Request
description: Request a new feature
title: "[FEATURE REQUEST]: "
labels: ["feature", "example"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: What would you like to see built?
    validations:
      required: true
